### ISSUE TITLE
Build Error - 

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-sls#26]
I dont know who is author for this module. Based on discussion with Sean, I need to assign to folks who contributed for this module.

Build Error Action 

https://github.com/cloud-native-toolkit/terraform-gitops-cp-sls/actions/runs/2310593734

╷
│ Error: Unsupported argument
│ 
│   on stage1-mongo.tf line 17, in module "mongo-operator":
│   17:   mongo_storageclass ="ibmc-vpc-block-10iops-tier"
│ 
│ An argument named "mongo_storageclass" is not expected here.
╵
Error: Process completed with exit code 1.

**Comment by tcskill** [comment]
@RamyaRaghuveera @balasgit ill look into it, I’ve totally re written this

**Comment by tcskill** [comment]
@balasgit this looks like an affect of the mongo module change from the storage class manager add after this was developed. Will update to reflect the new mongo module.
