### ISSUE TITLE
Build error - variables missing

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-sls#35]
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on .terraform/modules/mongo-operator.service_account.rbac/version.tf line 4, in terraform:
│    4:   experiments = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or
│ patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub
│ issue to discuss it.
│ 
│ (and 4 more similar warnings elsewhere)
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 87:
│   87: variable "mongo_dbpass" {
│ 
│ The root module input variable "mongo_dbpass" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.

**Comment by tcskill** [comment]
closed by #36
