### ISSUE TITLE
Remove the dependency on the cluster

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-gitops-cp-sls#4]
The module has a dependency on the cluster module for two values:
- ingress_subdomain value
- cluster_config_file

The `ingress_subdomain` value can be passed in as a simple string value.

The cluster config file is used to QUERY RESOURCES IN THE CLUSTER. This is a big no no. Any of the required values should either be passed in as variables OR queried from within the cluster using a job.

**Comment by tcskill** [comment]
closed in release v2.0.0 & v2.0.1 

[https://github.com/cloud-native-toolkit/terraform-gitops-cp-sls/releases/tag/v2.0.0](url)
